### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ghost** [towards-a-new-leftypol/leftypol_lainchan#1]
Here is a list of features outlined in this thread: https://www.leftypol.org/leftypol/res/30303.html

- [ ] Floating reply box
- [ ] Support for different file types (mp4, pdf, epub, etc....)
- [ ] Flags
- [ ] Embedding multiple files in a post
- [ ] Bunkerchan-like theme or a dark theme
- [ ] Threadwatcher
- [ ] Autorefresh
- [ ] Auto noko
- [ ] Inline reply
- [ ] Option for automatically archiving threads
- [ ] favicon

**Comment by towards-a-new-leftypol** [comment]
This list has been made into individual issues. Future features should be made into individual issues.

**Comment by towards-a-new-leftypol** [comment]
This list has been made into individual issues. Future features should be made into individual issues.
