### ISSUE TITLE
Add spoiler info to the API

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#100]
Adding an issue so it's easier to track updates.
It is in relation to this https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/91 and this https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/93 pull requests.

Tagging: @PietroCarrara

**Comment by nonmakina** [comment]
Responding to @PietroCarrara 's comment here: https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/93#issuecomment-754218944
I haven't seen the issue myself. The error we were seeing was `Undefined property: stdClass::$thumb in /srv/http/lainchan.leftypol.org/inc/api.php at line 96`

**Comment by nonmakina** [comment]
I implemented the feature in one of our test servers and couldn't reproduce it.

**Comment by nonmakina** [comment]
I tried it on the live production instance, and I got the same error.
I also tried with brackets [] and it didn't work. 
This works:
```
if (isset ($file->thumb) && $file->thumb) {
  $apiPost['spoiler'] = $file->thumb === 'spoiler' ? 1 : 0;
}
```

**Comment by PietroCarrara** [comment]
Maybe the thumb property is not set in the posts that were imported from bunkerchan? Either way, the solution looks good
