### ISSUE TITLE
Add new themes

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#105]
[Archive.zip](https://github.com/towards-a-new-leftypol/leftypol_lainchan/files/5773461/Archive.zip)

**Comment by dedushka1** [comment]
It looks like these were already requested in #38; do they differ from the ones provided in that issue?

**Comment by krates-leftypol** [comment]
Those are the most up to date versions of my custom themes.
[Demain_themes.zip](https://github.com/towards-a-new-leftypol/leftypol_lainchan/files/5826874/Demain_themes.zip)
