### ISSUE TITLE
Establish an Eepsite

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#109]
Antonius and I were speaking and we believe it would be beneficial to look into the development of an eepsite (i2p address) for leftypol.org. More information can be found about the creation of an eepsite @ https://medium.com/@mhatta/how-to-set-up-untraceable-websites-eepsites-on-i2p-1fe26069271d

**Comment by dedushka1** [comment]
Can we close this one and migrate to #144 for this issue?

**Comment by dedushka1** [comment]
Closing in favor of #144
