### ISSUE TITLE
Thumbnails for pdfs and ebooks

### ISSUE THREAD

**Issue by krates-leftypol** [towards-a-new-leftypol/leftypol_lainchan#110]
Make pdfs and ebooks have their cover for thumbnail.

**Comment by nonmakina** [comment]
Anon says:

For #110 PDF thumbnails set
`$config['pdf_file_thumbnail'] = true;`
`$config['djvu_file_thumbnail'] = true;`
and have imagemagick installed for the 'convert' command.
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/5ef52b3c71763defc7d551ebd27157e98a0d89fb/post.php#L1079
