### ISSUE TITLE
Clickable filenames (non-js)

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#128]
Issue https://github.com/towards-a-new-leftypol/leftypol_lainchan/issues/104 fixed this using JS. This issue tracks removing that js module and instead replacing it with a non-JS solution. 

A user says:

A quick fix to "download files with the original filename like on Bunkchan" >>36194 #104 is to change the text link line:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/5ef52b3c71763defc7d551ebd27157e98a0d89fb/templates/post/fileinfo.html#L10
```
> <p class="fileinfo">File: <a href="{{ config.uri_img }}{{ file.file }}" target="_blank">{{ file.file }}</a> <span class="details">
```
by replacing the target attribute with a download attribute set to the same expression that generates the full file name:
```
> <p class="fileinfo">File: <a href="{{ config.uri_img }}{{ file.file }}" {% if file.filename %}download="{{ file.filename|e|bidi_cleanup }}"{% else %}target="_blank"{% endif %}>{{ file.file }}</a> <span class="details">
```

However, with this quickfix the user is responsible for the sanity of the file name, and for its compatibility with the filesystem.

**Comment by nonmakina** [comment]
>There's no incompatibility between the two so there's no problem with leaving js/download-original.js active as well, should that be desired.

**Comment by discomrade** [comment]
Fixed https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/289
