### ISSUE TITLE
Gifs do not upload over tor

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#146]
There is a bug where gifs do not upload if you attempt to upload them over tor. This also breaks the formatting of the post slightly, I think

**Comment by nonmakina** [comment]
Is this a reliably reproducible bug?

**Comment by discomrade** [comment]
I have failed to reproduce this bug

**Comment by discomrade** [comment]
Closing as invalid,.gifs can definitely be uploaded over Tor.
