### ISSUE TITLE
When deleting a post you are redirected back to the board

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#151]
If you are inside a thread and you delete a post via the password it redirects you not back to the post, but, outside of the post back on the board. This is very inconvenient.

**Comment by nonmakina** [comment]
Almost feels like a UI bug? Tagged as feature request and bug.

**Comment by discomrade** [comment]
Fixed https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/285
