### ISSUE TITLE
Add a link to tv.leftypol.org to the Top Bar

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#152]
A user requested the we add a link to tv.leftypol.org on the top bar.
The argument being that it will increase traffic over the cytube instance and I am inclined to agree, so, I am adding this issue to the repo.

**Comment by nonmakina** [comment]
@xComatoast  How would this look? Like if it were a board?

**Comment by nonmakina** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/63084025/104870415-1617ba00-590e-11eb-94f0-0c54ad9d909a.png">
proposal.
