### ISSUE TITLE
Post history

### ISSUE THREAD

**Issue by krates-leftypol** [towards-a-new-leftypol/leftypol_lainchan#156]
Make the post history show every post of a user not just the recent ones.

**Comment by dedushka1** [comment]
This is a request for the moderator interface, right?

**Comment by krates-leftypol** [comment]
Yes

**Comment by nonmakina** [comment]
It shows the 5 most recent posts per board.

**Comment by nonmakina** [comment]
`$config['mod']['ip_recentposts']`
It is set using that.
