### ISSUE TITLE
Fix public log [privacy issue]

### ISSUE THREAD

**Issue by krates-leftypol** [towards-a-new-leftypol/leftypol_lainchan#162]
IPv6 are showing in the public logs.

**Comment by dedushka1** [comment]
Have you checked in a private session? Upon glance, it looks like mod log checks for permission. Only mods should see IP whether v4 or v6

**Comment by dedushka1** [comment]
Ok I see problem. Adding a IPv6 regex would be immediate fix but I like something more robust in future.
