### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by towards-a-new-leftypol** [towards-a-new-leftypol/leftypol_lainchan#2]
Related tasks

- [ ] Propose favicons (make thread asking for one?)
- [ ] Vote for a favicon
- [ ] Add the chosen one

**Comment by nonmakina** [comment]
We have cat alunya for now.

**Comment by towards-a-new-leftypol** [comment]
![alunya favicon](https://user-images.githubusercontent.com/76419376/103184010-d23c1280-4883-11eb-8e23-f937cafb6806.png)
using this atm

**Comment by nonmakina** [comment]
Closing due to lack of interest.
