### ISSUE TITLE
There are two conflicting PPH pull requests

### ISSUE THREAD

**Issue by towards-a-new-leftypol** [towards-a-new-leftypol/leftypol_lainchan#211]
There are two overlapping PR's:

https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/191/files
https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/200/files

So they both affect categories/news.html and categories/theme.php, so this isn't just a coincidence.

How shall we resolve this?

**Comment by nonmakina** [comment]
One commit works on top of the other. The pr #200 is forked from #191. Should #200 be accepted, #191 becomes moot.
