### ISSUE TITLE
Add a spoiler option in the quick reply box.

### ISSUE THREAD

**Issue by krates-leftypol** [towards-a-new-leftypol/leftypol_lainchan#213]
![Screenshot_20210124_220603](https://user-images.githubusercontent.com/77080062/105643490-0d803000-5e88-11eb-8791-8480e6da8758.png)

**Comment by krates-leftypol** [comment]
The quick reply spoiler #213 >>58745 can be fixed for the file-selector.js case by replacing the unconditional use of input[type="file"]:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/53769d8f3a966db48b4c8f562203187053e5fe59/js/quick-reply.js#L264


$postFormFile = $postForm.find('input[type="file"]');
if ($postFormFile.length) {
    $postForm.find('input[type="file"]').parent()
        .removeAttr('colspan')
        .after($('<td class="spoiler"></td>').append(this, ' ', $('<label for="q-spoiler-image">').text(_('Spoiler Image'))));
} else {
    $postForm.find('div.banner').append(' ', $('<span></span>').attr("title", _('Spoiler Image')).append(this, $('<label for="q-spoiler-image">').text("SI")));
}


Someone willing to fiddle with the #quick-reply CSS is welcome to place the spoiler in a different location. Until a backend fix the following can be added to Options -> User JS, since quick reply needs JS anyway:

(() => {
  const addspoiler = () => {
    $qr = $('#quick-reply')
    if (($qr.length == 0) || ($qr.find('input[name="spoiler"]').length != 0)) return;
    $qr.find('div.banner').append(' ', $('<span></span>').attr("title", _('Spoiler Image')).append($('<input id="q-spoiler-image" name="spoiler" type="checkbox">'), $('<label for="q-spoiler-image">').text("SI")))
  };
  addspoiler()
  $(window).on('quick-reply', addspoiler)
})()

**Comment by discomrade** [comment]
This appears to be fixed by https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/316/files#diff-e156e1a4ce7484ac4854b6711e4d7277d8d9a96b6095666a2d0b8e4fa1d24d68 . Closing.
