### ISSUE TITLE
Fixes for the Gurochan theme

### ISSUE THREAD

**Issue by NamelessRumia** [towards-a-new-leftypol/leftypol_lainchan#223]
For the `/stylesheets/gurochan.css` file, I would like the following to be added:

- Fixes the top bar not matching the bottom bar.
```
div.boardlist {
	color: #880000;
}
.bar.top {
	border-bottom: 1px solid #CA927B;
}
```

- Fixes outline for input boxes that aren't the comment box.
```
input[type="text"], input[type="password"], textarea {
	border: 1px solid #CA927B;
}
```

- Optional: Red tripcodes.
```
span.trip {
	color: #AF0A0F;
}
```

**Comment by krates-leftypol** [comment]
So like this :
[gurochan.zip](https://github.com/towards-a-new-leftypol/leftypol_lainchan/files/5898278/gurochan.zip)

?

**Comment by NamelessRumia** [comment]
Yeah, that's good.
