### ISSUE TITLE
Error when trying to move threads.

### ISSUE THREAD

**Issue by krates-leftypol** [towards-a-new-leftypol/leftypol_lainchan#225]
![Screenshot_20210130_170454](https://user-images.githubusercontent.com/77080062/106361371-81518b00-6315-11eb-8ef4-0b285a9b39c2.png)
"Unmovable thread" : https://leftypol.org/leftypol/res/48558.html

**Comment by towards-a-new-leftypol** [comment]
Seems fixed, that thread has been moved to /meta/ https://leftypol.org/meta/res/2865.html#63331
