### ISSUE TITLE
iconv() errors

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#23]
Users randomly experience a plethora of error messages related to iconv. iconv is a php extension that translates characters from one character set to another.

example:

iconv(): Unknown error (84) in /srv/http/lainchan.leftypol.org/inc/functions.php at line 2745

**Comment by nonmakina** [comment]
Example of character that triggers the issue:
`’`

**Comment by towards-a-new-leftypol** [comment]
Closing for now, please re-open this if we still see this in the wild.
