### ISSUE TITLE
basic mobile support

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#24]
add basic support for mobile devices.

suggestion from a user: "some basic mobile support for devices up to 768px width, add to end of /stylesheets/style.css

@media (max-width:768px) {
  #sidebar{display:none;}
  iframe#main{left: 0; border-left:none; width:100%;}
  .bar.bottom{opacity:0.8;}
  footer p.unimportant{display:none;}
}

a client-side js solution that checks browser user agent for mobile browser would be much better but this css workaround should do for now"

**Comment by nonmakina** [comment]
This seems innocuous enough, but the iframe is close to the chopping block. It'd be best if there were a more generic solution. 

Basic functionality for phone browsing seems like a high priority issue. Upgraded.

**Comment by nonmakina** [comment]
The iframe/sidebar is not longer an issue on mobile, as far as I am aware. I will close this issue.
