### ISSUE TITLE
Spam filter hitting tor

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#246]
We need to make the spam filter ignore tor requests as, with the continued growth of the site, using tor is becoming a hassle.

**Comment by discomrade** [comment]
Is this the flood limits? (How many posts by same IP within a time limit)
These have now been raised.

**Comment by discomrade** [comment]
Should be resolved by https://github.com/towards-a-new-leftypol/leftypol_lainchan/commit/862b7f55d3d0edf861351c7610084051e3073075
