### ISSUE TITLE
Add flag previews

### ISSUE THREAD

**Issue by RealCaballo** [towards-a-new-leftypol/leftypol_lainchan#256]
Redlidmilk pointed out that it would be nice if flags were previewed in the reply box when selecting one (as on bunkerchan/8chan) so you don't have to post to see what they look like. Obviously this is more of a long term want than a pressing need.

**Comment by discomrade** [comment]
Tested in dev, ready to deploy: https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/268

**Comment by discomrade** [comment]
Completed.
