### ISSUE TITLE
Broken links in frames/sidebar

### ISSUE THREAD

**Issue by NamelessRumia** [towards-a-new-leftypol/leftypol_lainchan#27]
Element and the Marxists Internet Archive doesn't allow linking in frames/sidebar.
If you absolutely must link to them, see if you can add `target="_blank"` into their `<a>` tags.

**Comment by nonmakina** [comment]
I personally detest the iframe/sidebar thing. I'd say we remove that functionality completely. It'd involve writing a simple home page.

**Comment by nonmakina** [comment]
Sidebar no longer uses iframes.
