### ISSUE TITLE
Orange text quoting

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#31]
The less than symbol or "<" should quote the text in a different color than normal, preferably orange, though subject to change based on theme/css.

**Comment by Barbara-Pitt** [comment]
according to anon:

To add the orange quotes of issue #31 look at the green quote line:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/64103eb6fc743d8c76496c41edac2901efb67c6d/inc/functions.php#L2208
> $body = preg_replace("/^\s*&gt;.*$/m", '<span class="quote">$0</span>', $body);
and add a new line after it:
> $body = preg_replace("/^\s*&lt;.*$/m", '<span class="orangequote">$0</span>', $body);
then add whatever styling you want to a span.orangequote css rule in the same way as for span.quote, e.g.:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/64103eb6fc743d8c76496c41edac2901efb67c6d/stylesheets/dark_red.css#L8

**Comment by nonmakina** [comment]
In `instance-config.php` add:
$config['markup'][] = array(regex, replace);

Green text quoting was at one point implemented with the following regex:
`"/(^|\n)([\s]+)?(&gt;)([^\n]+)?($|\n)/m"`
And was replaced with the following rule:
`'$1$2<span class="quote">$3$4</span>$5'`

Now, it is implemented like so:
`$body = preg_replace("/^\s*&gt;.*$/m", '<span class="quote">$0</span>', $body);`

Orange text could therefore be implemented in `instance-config.php` like this:
`$config['markup'][] = array("/^\s*&lt;.*$/m", '<span class="orangeText">$0</span>';`

**Comment by nonmakina** [comment]
The color should be `#FF8C00`
.orangeText {
  color: #FF8C00;
}
Pretty sure it's in `stylesheets/style.css`

Documenting all of this to make it easier to add more stuff in the future.
