### ISSUE TITLE
Theme picker is in the page footer

### ISSUE THREAD

**Issue by towards-a-new-leftypol** [towards-a-new-leftypol/leftypol_lainchan#319]
This is taking up too much space in the layout on mobile
![Screenshot_20210712-215447_20210712215911](https://user-images.githubusercontent.com/76419376/125378272-f83b8700-e37d-11eb-8baf-f50894c06d1c.png)

Probably the best way to fix this is to have that option never rendered out to the page by main.js (it could put json into a data attribute on an html element or something.

**Comment by xComatoast** [comment]
I liked it there, but, oh well.
