### ISSUE TITLE
Rebrand leftypol-lainchan

### ISSUE THREAD

**Issue by discomrade** [towards-a-new-leftypol/leftypol_lainchan#327]
We are now sufficiently divergent from lainchan software that we should update the README and site footers to reflect that we are now leftypol rather than lainchan.

This does not imply that this repo needs to change name or anything, just the site branding.

**Comment by towards-a-new-leftypol** [comment]
No, it's in the license that we can't edit the footer.

# From [LICENSE.md](https://github.com/lainchan/lainchan/blob/master/LICENSE.md):
```
All copyright notices and permission notices (including this file) shall be included and remain unedited in all copies or substantial portions of the Software. This explicitly includes but is not limited to the vichan copyright notices found in the footers of some template files.
```
