### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#358]
We must remove all the old banners related to the .org

**Comment by Zer0-** [comment]
Fixed here https://github.com/towards-a-new-leftypol/leftypol_lainchan/commit/d5bbcc205d4e357de180fa19d8d20e688d6153cb

**Comment by towards-a-new-leftypol** [comment]
Closed via https://github.com/towards-a-new-leftypol/leftypol_lainchan/commit/d5bbcc205d4e357de180fa19d8d20e688d6153cb
