### ISSUE TITLE
Implement webring

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#36]
Implement webring with /GET/ and bunkerchan + possible other sites

**Comment by nonmakina** [comment]
@Barbara-Pitt I don't think this is high priority and I expect this is a lot of work. I'll downgrade this issue for now and we can discuss it in the dev chat later.

**Comment by nonmakina** [comment]
never mind,  I don't have write permissions right now.

**Comment by Barbara-Pitt** [comment]
do the links to get/ref on top bar count as fixing this issue?

**Comment by nonmakina** [comment]
@Barbara-Pitt good question. I'm not sure what the status with that is right now.

**Comment by nonmakina** [comment]
Closing because of no actionable tasks.
