### ISSUE TITLE
Implement underlining

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#37]
Implement underlines using double underscore on each side
ex: __phrase words__

**Comment by Barbara-Pitt** [comment]
according to anon:

To add underlining for issue #37 look at the spoiler markup line:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/64103eb6fc743d8c76496c41edac2901efb67c6d/inc/config.php#L659
> $config['markup'][] = array("/\*\*(.+?)\*\*/", "<span class=\"spoiler\">\$1</span>");
then add a new line with:
> $config['markup'][] = array("/__(.+?)__/", "<span class=\"underline\">\$1</span>");
then add
> text-decoration: underline;
in a span.underline css rule to whichever stylesheet you want, e.g.:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/64103eb6fc743d8c76496c41edac2901efb67c6d/stylesheets/style.css#L606

**Comment by nonmakina** [comment]
This can be done with the `<u>` tag. What should the format for the markup rule be? 
`[space][underscore][text][underscore][space]` -> [space]`<u>`text`</u>`[space]
