### ISSUE TITLE
even more themes (user created)

### ISSUE THREAD

**Issue by Barbara-Pitt** [towards-a-new-leftypol/leftypol_lainchan#38]
anons want more themes.

1. "Demain Light" https://pastebin.com/faKcDHMQ
2. "Demain Dark" https://pastebin.com/Hkb8dEU4
3. "Temp Dark" https://pastebin.com/T3kiNKYQ
4. "Temp Dark Red" https://dpaste.com/EH4LBXYBT
5. "Tomorrow" https://pastebin.com/fF7d3Rp5
6. "Anons Dark Red" https://pastebin.com/316rtwUf

These are all user created

**Comment by nonmakina** [comment]
Should we just add them, or should we ask the mods what they think?

**Comment by dedushka1** [comment]
- [x]     "Demain Light" https://pastebin.com/faKcDHMQ
- [x]     "Demain Dark" https://pastebin.com/Hkb8dEU4
- [x]     "Temp Dark" https://pastebin.com/T3kiNKYQ
- [x]     "Temp Dark Red" https://dpaste.com/EH4LBXYBT
- [x]     "Tomorrow" https://pastebin.com/fF7d3Rp5
- [x]     "Anons Dark Red" https://pastebin.com/316rtwUf
