### ISSUE TITLE
Allow editing of posts by mods

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#47]
Does it leave a trace? 
eg. "edited by x mod on y date"

**Comment by towards-a-new-leftypol** [comment]
Is this fixed? If you have permissions but there are bugs with editing perhaps we can close this and track the editing glitches with https://github.com/towards-a-new-leftypol/leftypol_lainchan/issues/50

**Comment by nonmakina** [comment]
Yes. This is fixed.
