### ISSUE TITLE
Post flag data not included in JSON API

### ISSUE THREAD

**Issue by PietroCarrara** [towards-a-new-leftypol/leftypol_lainchan#68]
It is possible to see flags in posts while browsing the web version of the site, but it is not when using the API.

There should be fields like `country` (containing the flag name on the url, i.e 'gentoo', 'burkina_faso') and `country_name` (The user-readable flag name, i.e. 'Gentoo', 'Burkina Faso')

The mobile app needs these fields in order to display flags

**Comment by nonmakina** [comment]
Marking this as `high priority`. Custom flags are important for the site, and by extension, to the mobile app users.
