### ISSUE TITLE
Twitch re-stream

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#74]
Potentially using cytube's libraries. 

The suggestion:
">After months of waiting for an answer, Twitch has explained that cytu.be is banned from embedding Twitch due to allegedly violating the Twitch Terms of Service/Community Guidelines. Users wishing to embed Twitch streams are welcome to host their own website based on CyTube's open source code.
its possible for this to happen now that we have a site. restream twitch finally.
"

**Comment by towards-a-new-leftypol** [comment]
via tv.leftypol.org
