### ISSUE TITLE
Onion-Location headers.

### ISSUE THREAD

**Issue by xComatoast** [towards-a-new-leftypol/leftypol_lainchan#75]
https://community.torproject.org/onion-services/advanced/onion-location/

Onion-Location is an easy way to advertise an onion site to the users. You can either configure a web server to show an Onion-Location Header or add an HTML meta attribute in the website.

For the header to be valid the following conditions need to be fulfilled:

    The Onion-Location value must be a valid URL with http: or https: protocol and a .onion hostname.
    The webpage defining the Onion-Location header must be served over HTTPS.
    The webpage defining the Onion-Location header must not be an onion site.

In this page, the commands to manage the web server are based Debian-like operating systems and may differ from other systems. Check your web server and operating system documentation...

**Comment by towards-a-new-leftypol** [comment]
@420blazeitbeepbeepletus Can you please confirm that we don't already have this live? Here is a GET response to leftypol with the headers that I get:

```
HTTP/2 200 OK
date: Thu, 31 Dec 2020 08:05:06 GMT
content-type: text/html
last-modified: Thu, 31 Dec 2020 07:59:02 GMT
onion-location: http://wz6bnwwtwckltvkvji6vvgmjrfspr3lstz66rusvtczhsgvwdcixgbyd.onion/leftypol/index.html
cf-cache-status: DYNAMIC
cf-request-id: 07596d4c520000f97d6a8ec000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=WhSfhFz1CcDLF29HTtRcb4TfS7CGr%2Bw3sZfrpZJ3bQ9yArD7e7InhgwNKKg5vS5Jrb7L9Gykq6z7MGQ05V8sVMIXMxFgdxh0ViT%2BQvw%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 60a27e5a19a6f97d-YYZ
content-encoding: gzip
X-Firefox-Spdy: h2
```
