### ISSUE TITLE
(Alleged) Cache issues

### ISSUE THREAD

**Issue by nonmakina** [towards-a-new-leftypol/leftypol_lainchan#88]
"I post, then it supposedly takes me to my post theead.html#some number, but it doesn't show up in the thread. I update, I refresh, I reload, nothing. "

Quick research seems to confirm that cloudflare cache is indeed the problem.

Solution might involve setting cloudflare's cache settings to respect origin header, and then setting all media (and other static files, eg js and css), and setting a shorter TTL to html pages.
https://www.techrepublic.com/article/how-to-cache-static-content-on-nginx/

**Comment by nonmakina** [comment]
Update: cache issues are mostly fixed. There are some JS issues we're dealing with now.

**Comment by towards-a-new-leftypol** [comment]
The "JS" issue we are dealing with is that the subsequent GET request after a POST isn't guaranteed to have the latest post. See the comments here: https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/97
