### ISSUE TITLE
Fix Quick Reply transparency for Gentoochan

### ISSUE THREAD

**Issue by NamelessRumia** [towards-a-new-leftypol/leftypol_lainchan#90]
The quick reply box is transparent when it's dragged over posts in the Gentoochan theme, making it difficult to read.
An easy fix would be going to the `/stylesheets/gentoochan.css` file and inserting one of the following:

- **Plain background with better transparency**:
```
#quick-reply table {
	background: rgba(240,240,240,0.95) !important;
}
```

- **Plain background with no transparency**:
```
#quick-reply table {
	background: #f0f0f0 !important;
}
```

- **Same background as theme**:
```
#quick-reply table {
	background: #0E0E0E url(data:image/gif;base64,R0lGODlhGAAMAKEEAOXl5ebm5vDw8PHx8SH+EUNyZWF0ZWQgd2l0aCBHSU1QACwAAAAAGAAMAAACRpQiY6cLa146MyY1EJQKjG81lNGRUPOIkgMJHtquBgIO7xwvpbrpduUSuXq8ntEC0bBEylYitdDAdM1ViaobkgKgZwyDLAAAOw==) repeat 0 0 !important;
}
```

**Comment by nonmakina** [comment]
I'll look into this tomorrow hopefully.

**Comment by nonmakina** [comment]
I liked the third one the most.
