### ISSUE TITLE
Antispam feature is broken for some users

### ISSUE THREAD

**Issue by towards-a-new-leftypol** [towards-a-new-leftypol/leftypol_lainchan#96]
This feature was turned off in [this pull request](https://github.com/towards-a-new-leftypol/leftypol_lainchan/pull/94) however if we ever need it again, we should make sure it won't cause issues for users.

One approach could be to put log statements in that logic and turn it on for a short period of time, and analyze the logs.

**Comment by towards-a-new-leftypol** [comment]
Zul says:

>other possibility: time format. 
>both spragga and this guy live in someplace where they write the date/time weird
>haven't seen any "i can't post at all" comments from any americans

**Comment by nonmakina** [comment]
Duplicate:
https://github.com/towards-a-new-leftypol/leftypol_lainchan/issues/87
